#######################
# Basic Configuration #
#######################
# spring.application.name
# app.name
# app.version
#     These variables should not be changed, as they pull in variables from pom.xml.  To get these variables to
#     show appropriately in the app, ensure that you set the following environment variable prior to running the
#     app:
#          export SPRING_CONFIG_LOCATION=classpath:application.properties,file:///path/to/eCarePlan/config/files/
#     See https://github.com/OHSUCMP/eCarePlan/issues/152 for details.
spring.application.name=@project.artifactId@
app.name=@project.artifactId@
app.version=@project.version@
# logging.config
#     Specifies the location of the 'logback.xml' file, which defines how and where eCarePlan writes logfile data.
# logging.config=file:///path/to/eCarePlan/config/files/logback.xml
logging.config=classpath:logback.xml
# server.port
#     Specifies the network port on which eCarePlan listens.
#     This should NOT be port 8080 (which is the default), because CQF-Ruler - an auxiliary system on which eCarePlan
#     depends in order to run recommendations, and which is recommended to run on the same server as eCarePlan - is
#     hard-coded to listen on port 8080.  As such, eCarePlan must listen on a different port so as to avoid conflicts.
server.port=8088
# socket.timeout
#     This property defines how many milliseconds eCarePlan will wait for network operations to respond.
#     3600000ms = 3600 seconds = 60 minutes = 1 hour
socket.timeout=3600000
# spring.mvc.async.request-timeout
#     Amount of time before asynchronous requests timeout, in milliseconds.
#     3600000ms = 3600 seconds = 60 minutes = 1 hour
spring.mvc.async.request-timeout=3600000


###################################
# eCarePlan System Status Message #
###################################
# system.status-message
#     If present, this message will be displayed prominently to users at the top of the home page.
system.status-message=


#########################
# SSL/TLS Configuration #
#########################
# This section defines SSL and TLS configuration to enable eCarePlan to serve encrypted traffic.
# See https://www.baeldung.com/spring-tls-setup for details and instructions on how to configure these properties.
server.ssl.enabled=false
server.ssl.key-store-password=change_me!
server.ssl.key-store=file:///git/ecareplan-sbe/ssl/localhost-ssl.p12
server.ssl.key-store-type=PKCS12
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2


################################
# Other Security Configuration #
################################
# security.salt
#     This property should contain a string of random characters and be at least 32 characters in length.
#     It is used by eCarePlan when generating hash values for generated resource IDs and database records, as appropriate.
security.salt=CHANGE_THIS_BEFORE_RUNNING_IN_PRODUCTION
# security.show-dev-errors
#     If true, errors generated by the recommendation engine will be displayed.
#     If false, a generic error is displayed instead.
#     It is recommended that this property be set to 'true' in a development environment, and 'false' in production.
security.show-dev-errors=false
# security.browser.cache-credentials
#     If 'true', the browser will cache FHIR credentials, facilitating reloading of the eCarePlan application.  However,
#     doing so presents a potential security risk, as these credentials are sensitive in nature.  As such, it is
#     recommended that this be set to 'true' in development environments, and 'false' in production ones.
security.browser.cache-credentials=false
# security.idle-timeout-seconds
#     This property specifies the number of seconds of inactivity that must occur for a user to be automatically
#     logged out of eCarePlan.  If specified, it must be a number > 60, as the last 60 seconds will always be displayed in
#     a modal dialog to the user with a 60-second countdown that the user can abort if they so desire.  Specifying a
#     value that is smaller than 60 will cause the modal dialog to appear immediately.  If this is set to 0, the idle
#     timeout is disabled.
# security.idle-timeout-seconds=900
security.idle-timeout-seconds=0


####################################
# eCarePlan Database Configuration #
####################################
# The following configurations are used to define how to connect to the eCarePlan database.
# At this time, MySQL and Microsoft SQL Server are supported.
# spring.datasource.driverClassName
#     This property defines the driver to use to connect to the target database.  Both MySQL and Microsoft SQL Server
#     drivers are provided (default MySQL):
# spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# spring.datasource.url
#     This property defines the connection string that should be usec to connect to the target database.  Both MySQL
#     and Microsoft SQL Server URLs are provided, and which may need to be modified based on implementation details
#     (default MySQL):
# spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=ecareplan;encrypt=false
spring.datasource.url=jdbc:mysql://localhost:3306/ecareplan
# spring.datasource.username
#     This is the username for the database user that should be used to connect to the target database
spring.datasource.username=ecareplan
# spring.datasource.password
#     This is the password for the database user specified above
spring.datasource.password=CHANGE_THIS_in_PRODUCTION!


##########################
# Endpoint Configuration #
##########################
# This section defines endpoint configurations.  These will need to match configurations as dictated by the FHIR
# server(s) that eCarePlan will be interacting with.
# endpoint.patientLaunch.name
#     This property defines the name of the Patient Launch endpoint in the endpoint table in the database.  A record
#     with this name must exist in the endpoint table in order to launch the application in the Patient context.
#     Please ensure that such a record exists and is appropriately defined.
endpoint.patientLaunch.name=Patient Launch
# endpoint.careTeamLaunch.name
#     This property defines the name of the Care Team Launch endpoint in the endpoint table in the database.  A record
#     with this name must exist in the endpoint table in order to launch the application in the Care Team context.
#     Please ensure that such a record exists and is appropriately defined.
endpoint.careTeamLaunch.name=Care Team Launch
# endpoint.sds.name
#     This property defines the name of the SDS endpoint in the endpoint table in the database.  A record with this
#     name must exist in the endpoint table in order for the application to communicate with the SDS.
#     Please ensure that such a record exists and is appropriately defined.
endpoint.sds.name=SDS


##################################################################
# SMART-on-FHIR Backend / System-to-System Context Configuration #
##################################################################
# This section is used to configure a backend, or system-to-system SMART-on-FHIR configuration, which is required
# for vitals writebacks in many systems, and to retrieve (the optional but useful) ServiceRequest resources.
#
# smart.backend.clientId
#     This is the FHIR client ID that should be used for operations and queries that employ the BACKEND context.
#     This may be left blank if BACKEND context is not used.
smart.backend.clientId=
# smart.backend.iss
#     This stores the base FHIR API endpoint that eCarePlan will use with backend / system-to-system operations.  If this
#     property is left blank, the active iss that was used to launch eCarePlan will be used instead.
smart.backend.iss=
# smart.backend.scope
#     This stores the scope that will be used for backend operations.  If provided, this will become a claim in the
#     JWT, and in the access token request payload.
smart.backend.scope=
# If any FHIR "strategy" is configured to use the BACKEND context, and that context requires use of a JSON Web Token
# (JWT), those configurations must be set here.
# For Epic environments, see https://vendorservices.epic.com/Article/Index?docId=oauth2&section=BackendOAuth2Guide
#
# Instructions to create RSA keys using OpenSSL:
# NOTE: replace {ENV} with some identifier indicating the environment (e.g. "test", "prod", etc.)
#
# 1. Create 3072-bit RSA private key:
#       openssl genrsa -out eCarePlan-backend-{ENV}-privatekey.pem 3072
# 2. Export public key to base64 encoded X.509 certificate:
#       openssl req -new -x509 -key eCarePlan-backend-{ENV}-privatekey.pem -out eCarePlan-backend-{ENV}-publickey509.pem \
#           -subj '/CN=eCarePlan-backend-{ENV}'
# 3. Convert private key from PKCS1 to PKCS8 format:
#       openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in eCarePlan-backend-{ENV}-privatekey.pem \
#           -out eCarePlan-backend-{ENV}-privatekey-pkcs8.pem
#
# smart.backend.jwt.x509-certificate-file
#     This stores the filesystem location for where the x509 public certificate file can be found, associated with
#     the JWT.
# smart.backend.jwt.x509-certificate-file=/path/to/eCarePlan-backend-publickey509.pem
smart.backend.jwt.x509-certificate-file=
# smart.backend.jwt.pkcs8-private-key-file
#     This stores the filesystem location for where the PKCS8 private key file can be found, associated with the JWT.
# smart.backend.jwt.pkcs8-private-key-file=/path/to/eCarePlan-backend-privatekey-pkcs8.key
smart.backend.jwt.pkcs8-private-key-file=
# smart.backend.basic-auth.secret
#     This stores a secret that will be used to obtain an access token using basic authentication.  It is only
#     considered if smart.backend.jwt configurations are not set, which is the preferred strategy.
smart.backend.basic-auth.secret=

#####################
# SDS Configuration #
#####################
sds.endpoint=http://localhost:8080/fhir
sds.scope="launch/patient openid fhirUser patient/*.read patient/*.write"


############################
# Basic FHIR Configuration #
############################
# This section defines basic configuration settings that relate to FHIR services.
# fhir.search.count
#     This is the maximum number of FHIR resources to be retrieved per request.  If more than 1000 records are
#     found, the system will request additional pages.
fhir.search.count=1000


###################################
# Advanced Configuration Settings #
###################################
# This section defines configurations that drive core parts of eCarePlan system operation.  It is recommended to not
# change these settings unless you really know what you're doing.
spring.flyway.locations=classpath:db/migration/{vendor}
spring.mustache.expose-request-attributes=true
spring.mustache.request-context-attribute=req
spring.mustache.expose-session-attributes=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.main.allow-bean-definition-overriding=true
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_query_cache=false
