package edu.ohsu.cmp.ecareplan.service;

import edu.ohsu.cmp.ecareplan.model.report.IReport;
import jakarta.annotation.PostConstruct;
import jakarta.mail.Address;
import jakarta.mail.internet.AddressException;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSenderImpl;
import org.springframework.stereotype.Service;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.List;
import java.util.Objects;

@Service
public class ReportService extends BaseService {
    private static final Logger logger = LoggerFactory.getLogger(ReportService.class);

    @Value("#{new Boolean('${report.enabled}')}")
    private Boolean enabled;

    @Value("${report.smtp-host}")
    private String smtpHost;

    @Value("#{'${report.recipient-email-list.csv}'.split(',')}")
    private List<String> recipientEmailList;

    @Value("${report.subject-prefix:}")
    private String subjectPrefix;

    private final JavaMailSenderImpl mailSender;
    private final String fromAddress;
    private Address[] recipients;

    public ReportService() {
        mailSender = new JavaMailSenderImpl();

        try {
            fromAddress = "noreply@" + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException e) {
            throw new RuntimeException(e);
        }
    }

    @PostConstruct
    public void init() {
        mailSender.setHost(smtpHost);

        recipients = buildRecipients(recipientEmailList);
    }

    private Address[] buildRecipients(List<String> emailList) {
        return emailList.stream().map(email -> {
            try {
                return new InternetAddress(email);
            } catch (AddressException e) {
                logger.error("Invalid email address: {}", email, e);
                return null;
            }
        }).filter(Objects::nonNull).toArray(Address[]::new);
    }

    public Boolean isEnabled() {
        return enabled;
    }

    public void sendReport(IReport report) {
        if (enabled && ! recipientEmailList.isEmpty()) {
            final String bodyHeader = "<p>This email was auto-generated by the eCarePlan-SBE system.  Please do not reply.</p>\n" +
                    "<p><strong><span style='color: red;'>This is an unredacted email and may contain PHI.  Do not forward this email.</span></strong></p>\n";

            try {
                MimeMessage mimeMessage = mailSender.createMimeMessage();
                mimeMessage.setFrom(fromAddress);
                mimeMessage.setRecipients(MimeMessage.RecipientType.TO, recipients);
                mimeMessage.setSubject(subjectPrefix + " " + report.getTitle());
                mimeMessage.setText(bodyHeader + report.getBody());

                mailSender.send(mimeMessage);

            } catch (Exception e) {
                logger.error("Failed to send report", e);
            }
        }
    }
}
